In [28]:
import numpy as np

def X(N): return np.random.randint(100, size=(N, N))

def Y(N): return np.random.randint(100, size=(N, N + 1))

def multiply(X, Y): return np.matmul(X, Y)

def print_results(result): print(result)

In [40]:
%load_ext line_profiler

The line_profiler extension is already loaded. To reload it, use:
  %reload_ext line_profiler
The memory_profiler extension is already loaded. To reload it, use:
  %reload_ext memory_profiler


In [41]:
N = 250
%lprun -f X print_results(multiply(X(N), Y(N)))
%mprun -f X print_results(multiply(X(N), Y(N)))

[[658759 613582 622393 ... 611274 645502 597822]
 [654954 603599 613277 ... 601799 617460 587756]
 [653077 615611 607415 ... 588477 659029 609263]
 ...
 [690413 671717 674948 ... 658439 683715 662760]
 [631920 601382 643435 ... 584330 642169 609678]
 [630836 575490 601081 ... 589309 611697 571958]]
ERROR: Could not find file <ipython-input-28-8b84b085e88c>
NOTE: %mprun can only be used on functions defined in physical files, and not in the IPython environment.
[[606909 632656 581928 ... 599872 582606 608506]
 [587764 595356 567982 ... 589743 572498 569426]
 [604112 608418 625780 ... 625105 604461 608976]
 ...
 [583352 580593 568724 ... 592265 553462 592936]
 [602085 595453 578372 ... 602763 571789 593392]
 [601995 629014 584044 ... 580105 584411 584540]]



In [35]:
%lprun -f Y print_results(multiply(X(N), Y(N)))

[[629034 648829 624932 ... 639637 648809 695337]
 [599772 596351 564542 ... 608213 605848 676087]
 [605327 631172 632952 ... 640816 647501 670121]
 ...
 [604423 611266 591560 ... 623792 604599 633987]
 [587739 598630 550434 ... 590183 575219 658695]
 [603339 594096 621800 ... 667674 638883 688038]]


In [37]:
%lprun -f multiply print_results(multiply(X(N), Y(N)))

[[588130 598846 593980 ... 658089 572782 625383]
 [546763 591868 569842 ... 644761 583233 596390]
 [581439 626915 573644 ... 616981 546605 603053]
 ...
 [560730 602485 558351 ... 618167 582033 597801]
 [622606 635078 643149 ... 690357 643132 666433]
 [630524 618156 606441 ... 677123 622383 671532]]


In [38]:
%lprun -f print_results print_results(multiply(X(N), Y(N)))

[[637928 609756 657742 ... 654533 692823 635938]
 [608251 601209 643048 ... 643019 681236 610939]
 [633324 642548 649083 ... 669721 701633 668265]
 ...
 [626617 627737 668073 ... 651477 692180 651189]
 [647125 651888 674523 ... 660464 685172 666104]
 [599564 574077 620005 ... 609241 643805 618997]]
