In [3]:
import numpy as np

a = np.zeros(10)
a[4] = 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
b = np.arange(10, 50)
print(b)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
c = b[::-1]
print(c)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [25]:
d = np.arange(0, 9).reshape(3, 3)
print(d)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [15]:
e = np.array([1, 2, 0, 0, 4, 0])
print(np.where(e > 0))

(array([0, 1, 4]),)


In [29]:
f = np.random.randint(100, size=30)
print(np.mean(f))

44.766666666666666


In [216]:
g = np.zeros((5, 5))
g[:, [0, -1]] = 1
g[[0, -1], :] = 1
print(g)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]]


In [125]:
h = np.zeros((8, 8))
h[::2, :][:,::2] = 1
h[1::2, :][:,1::2] = 1
print(h)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [168]:
i = np.zeros(8)
N = int(len(i)/2)
i[::2] = 1
i_mat = np.tile(np.array([i, i[::-1]]), (N, 1))
print(i_mat)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [263]:
j = np.arange(11)
j[(j > 3) & (j < 8)] = -j[(j > 3) & (j < 8)]
print(j)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


In [229]:
h = np.random.random(10)
h = np.sort(h)
print(h)

[0.03452971 0.08019735 0.09717718 0.28212304 0.44728846 0.57735093
 0.58830915 0.66325939 0.70899538 0.89511943]


In [238]:
l1 = np.random.randint(0,2,5)
l2 = np.random.randint(0,2,5)
equal = np.all(l1 == l2)
print(equal)

False


In [242]:
m = np.arange(10, dtype=np.int32)
m = m.astype("float32")
print(m.dtype)

float32


In [256]:
n1 = np.arange(9).reshape(3,3)
n2 = n1 + 1
n3 = np.dot(n1,n2)
diagonal = np.diagonal(n3) 
n = np.arange(len(n3))
diagonal2 = n3[n,n]
print(diagonal)
print(diagonal2)

[ 18  66 132]
[ 18  66 132]
